theme: minima
title: Your awesome title
author: WIZONCEMarcus
email: forizone9201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I will love IZ\*ONE forever.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
